[package]
name = "memphis-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nats = "0.24.0"
rand = "0.8.5"
serde = "1.0.160"
serde_json = "1.0.96"
