[package]
name = "consumer"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.29", features = ["full"] }
env_logger = "0.10"
memphis-rust-community = { path = "../.." }
