name: CD

on:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Rust
        uses: actions/cache@v3
        env:
          cache-name: cache-rust
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.toml') }}

      - name: Install Rust
        run: |
          rustup install nightly
          rustup default nightly

      - name: Build
        run: |
          cargo build --release --all-features

      - name: Publish
        run: |
          cargo login ${{ secrets.RUST_API_KEY }}
          cargo publish --token ${{ secrets.RUST_API_KEY }} --all-features
