name: CI
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  check_test_latest:
    name: check (test) on latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Rust
        uses: actions/cache@v3
        env:
          cache-name: cache-rust
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.toml') }}

      - name: Setup Memphis Latest
        run: |
          curl -sSL https://raw.githubusercontent.com/memphisdev/memphis-docker/master/docker-compose-latest.yml > docker-compose.yml
          docker-compose up -d

      - name: Install Rust
        run: |
          rustup install nightly
          rustup default nightly

      - name: Run Tests
        env:
          RUST_TEST_TIME_UNIT: 60000,120000
          RUST_TEST_TIME_INTEGRATION: 60000,120000
          RUST_TEST_TIME_DOCTEST: 60000,120000
          RUST_LOG: trace
        run: |
          cargo test --workspace --all-targets --all-features -- --ensure-time --report-time -Z unstable-options


  check_test_stable:
    name: check (test) on stable
    runs-on: ubuntu-latest
    needs:
      - check_test_latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Rust
        uses: actions/cache@v3
        env:
          cache-name: cache-rust
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.toml') }}

      - name: Setup Memphis Stable
        run: |
          curl -sSL https://raw.githubusercontent.com/memphisdev/memphis-docker/master/docker-compose.yml > docker-compose.yml
          docker-compose up -d

      - name: Install Rust
        run: |
          rustup install nightly
          rustup default nightly

      - name: Run Tests
        env:
          RUST_TEST_TIME_UNIT: 60000,120000
          RUST_TEST_TIME_INTEGRATION: 60000,120000
          RUST_TEST_TIME_DOCTEST: 60000,120000
          RUST_LOG: trace
        run: |
          cargo test --workspace --all-targets --all-features -- --ensure-time --report-time -Z unstable-options


  check_format:
    name: check (format)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Rust
        run: |
          rustup install nightly
          rustup default nightly
          rustup component add rustfmt

      - name: Run the check
        run: cargo fmt -- --check
  check_lint:
    name: check (lint)
    runs-on: ubuntu-latest
    steps:
      - name: Cache rust
        uses: actions/cache@v3
        env:
          cache-name: cache-rust
        with:
          path: target
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Rust
        run: |
          rustup install nightly
          rustup default nightly
          rustup component add clippy

      - name: Check lint
        run: cargo clippy --benches --tests --examples --all-features -- --deny clippy::all
  check_docs:
    name: check (docs)
    runs-on: ubuntu-latest
    steps:
      - name: Cache rust
        uses: actions/cache@v3
        env:
          cache-name: cache-rust
        with:
          path: target
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up rust
        run: |
          rustup install nightly
          rustup default nightly
          rustup component add clippy

      - name: Check lint
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --workspace --all-features
